language: node_js

node_js:
  - 8

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    - stage: docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        script: npx deploy:docz
        on:
          branch: master